### ISSUE TITLE
Show Cases

### ISSUE THREAD

**Issue by nandosangenetto** [jaanauati/react-dfp#37]
There's show cases?

It's safe for production? And with SSR?

**Comment by slackday** [comment]
Safe for production I would say no.

I'm struggling with implementing this. I would also be interested in show cases. I tried replying to this closed issue https://github.com/jaanauati/react-dfp/issues/14 because I'm facing the same problem when AdSlot component is unmounted and mounted again when navigating to another page.

Initial page load is fine. But I can't try this in production while having this issue.

![screen shot 2017-09-19 at 20 44 17](https://user-images.githubusercontent.com/154369/30609393-9cb10794-9d7b-11e7-96fc-72c20db5a48e.png)

**Comment by jaanauati** [comment]
hey @nandosangenetto, thanks for flagging on this, we show cases you are referring to examples? yeah, i'm aware of it (https://github.com/jaanauati/react-dfp/issues/10), i just wish i have some time in the following months to add couple.... meantime, you might have a look at the example provided in the readme file... just surround your app -and/or- slots with an instante of <DFPSlotsProvider>:
```<DFPSlotsProvider args... >
<app-component ...>
  ....
  <AdSlot args...>
   ....
  <AdSlot args...>
   ... and so on
</app-component>
</DFPSlotsProvider>
```

@slackday i hear you, but out of the scope of this tx,  I would encourage you to either file a bug or, if you are certain that the same error popped, to reopen the already existent issue, and please provide some code that hopefully helps to replicate the bug, pull requests are also welcome :-).

**Comment by slackday** [comment]
Sorry if I was a bit off-topic and blunt maybe in my comment. I deleted it. I tried to re-create the problem in a clean codebase but was unsuccessful. So I guess it's an issue with my app. Sorry for the concern :)

**Comment by jaanauati** [comment]
@slackday no worries man, were u finally able to finally able to overcome your issues?....  i've been working out some code examples that I plan to push in the following weeks. 
thanks.
